/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppContractsNewRouteImport } from './routes/_app/contracts/new'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppContractsContractIdIndexRouteImport } from './routes/_app/contracts/$contractId/index'
import { Route as AppContractsContractIdVistoriaImagemRouteImport } from './routes/_app/contracts/$contractId/vistoria-imagem'
import { Route as AppContractsContractIdTimelineRouteImport } from './routes/_app/contracts/$contractId/timeline'
import { Route as AppContractsContractIdSubcontratosRouteImport } from './routes/_app/contracts/$contractId/subcontratos'
import { Route as AppContractsContractIdRmaRouteImport } from './routes/_app/contracts/$contractId/rma'
import { Route as AppContractsContractIdPlanoAcaoRouteImport } from './routes/_app/contracts/$contractId/plano-acao'
import { Route as AppContractsContractIdNormalizacaoRouteImport } from './routes/_app/contracts/$contractId/normalizacao'
import { Route as AppContractsContractIdMelhoriasDocRouteImport } from './routes/_app/contracts/$contractId/melhorias-doc'
import { Route as AppContractsContractIdMapeamentoRouteImport } from './routes/_app/contracts/$contractId/mapeamento'
import { Route as AppContractsContractIdMapaRouteImport } from './routes/_app/contracts/$contractId/mapa'
import { Route as AppContractsContractIdExtracaoRouteImport } from './routes/_app/contracts/$contractId/extracao'
import { Route as AppContractsContractIdDashboardRouteImport } from './routes/_app/contracts/$contractId/dashboard'
import { Route as AppContractsContractIdCondutasRouteImport } from './routes/_app/contracts/$contractId/condutas'
import { Route as AppContractsContractIdChatRouteImport } from './routes/_app/contracts/$contractId/chat'
import { Route as AppContractsContractIdBibliotecaRouteImport } from './routes/_app/contracts/$contractId/biblioteca'
import { Route as AppContractsContractIdRmaIndexRouteImport } from './routes/_app/contracts/$contractId/rma/index'
import { Route as AppContractsContractIdDesequilibrioIndexRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/index'
import { Route as AppContractsContractIdControleDocumentalIndexRouteImport } from './routes/_app/contracts/$contractId/controle-documental/index'
import { Route as AppContractsContractIdContabilIndexRouteImport } from './routes/_app/contracts/$contractId/contabil/index'
import { Route as AppContractsContractIdChecklistIndexRouteImport } from './routes/_app/contracts/$contractId/checklist/index'
import { Route as AppContractsContractIdRmaVisaoGeralRouteImport } from './routes/_app/contracts/$contractId/rma/visao-geral'
import { Route as AppContractsContractIdRmaResponsabilidadeRouteImport } from './routes/_app/contracts/$contractId/rma/responsabilidade'
import { Route as AppContractsContractIdRmaRecursosRouteImport } from './routes/_app/contracts/$contractId/rma/recursos'
import { Route as AppContractsContractIdRmaProdutividadeRouteImport } from './routes/_app/contracts/$contractId/rma/produtividade'
import { Route as AppContractsContractIdRmaPrazoRouteImport } from './routes/_app/contracts/$contractId/rma/prazo'
import { Route as AppContractsContractIdRmaPlanoAcaoRouteImport } from './routes/_app/contracts/$contractId/rma/plano-acao'
import { Route as AppContractsContractIdRmaPanoramaRouteImport } from './routes/_app/contracts/$contractId/rma/panorama'
import { Route as AppContractsContractIdRmaInsumosRouteImport } from './routes/_app/contracts/$contractId/rma/insumos'
import { Route as AppContractsContractIdRmaIndicadoresRouteImport } from './routes/_app/contracts/$contractId/rma/indicadores'
import { Route as AppContractsContractIdRmaFaturamentoRouteImport } from './routes/_app/contracts/$contractId/rma/faturamento'
import { Route as AppContractsContractIdRmaCurvasRouteImport } from './routes/_app/contracts/$contractId/rma/curvas'
import { Route as AppContractsContractIdRmaCondutasRouteImport } from './routes/_app/contracts/$contractId/rma/condutas'
import { Route as AppContractsContractIdRmaChuvasRouteImport } from './routes/_app/contracts/$contractId/rma/chuvas'
import { Route as AppContractsContractIdPreTranspasseRouteImport } from './routes/_app/contracts/$contractId/pre/transpasse'
import { Route as AppContractsContractIdPreRevisaoRouteImport } from './routes/_app/contracts/$contractId/pre/revisao'
import { Route as AppContractsContractIdPreDiagnosticoRouteImport } from './routes/_app/contracts/$contractId/pre/diagnostico'
import { Route as AppContractsContractIdPreBasesRouteImport } from './routes/_app/contracts/$contractId/pre/bases'
import { Route as AppContractsContractIdFinalizacaoPleitosRouteImport } from './routes/_app/contracts/$contractId/finalizacao/pleitos'
import { Route as AppContractsContractIdFinalizacaoLicoesRouteImport } from './routes/_app/contracts/$contractId/finalizacao/licoes'
import { Route as AppContractsContractIdFinalizacaoJudicialRouteImport } from './routes/_app/contracts/$contractId/finalizacao/judicial'
import { Route as AppContractsContractIdDesequilibrioValorAgregadoRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/valor-agregado'
import { Route as AppContractsContractIdDesequilibrioPontuaisRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/pontuais'
import { Route as AppContractsContractIdDesequilibrioInsumosRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/insumos'
import { Route as AppContractsContractIdDesequilibrioIndiretosRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/indiretos'
import { Route as AppContractsContractIdDesequilibrioGeradorClaimRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/gerador-claim'
import { Route as AppContractsContractIdDesequilibrioEncargosRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/encargos'
import { Route as AppContractsContractIdDesequilibrioBdiRouteImport } from './routes/_app/contracts/$contractId/desequilibrio/bdi'
import { Route as AppContractsContractIdControleDocumentalOperacaoRouteImport } from './routes/_app/contracts/$contractId/controle-documental/operacao'
import { Route as AppContractsContractIdControleDocumentalDocumentosRouteImport } from './routes/_app/contracts/$contractId/controle-documental/documentos'
import { Route as AppContractsContractIdControleDocumentalAreasRouteImport } from './routes/_app/contracts/$contractId/controle-documental/areas'
import { Route as AppContractsContractIdContabilPericialRouteImport } from './routes/_app/contracts/$contractId/contabil/pericial'
import { Route as AppContractsContractIdContabilOperacaoRouteImport } from './routes/_app/contracts/$contractId/contabil/operacao'
import { Route as AppContractsContractIdContabilCapituloRouteImport } from './routes/_app/contracts/$contractId/contabil/capitulo'
import { Route as AppContractsContractIdChecklistSetorRouteImport } from './routes/_app/contracts/$contractId/checklist/$setor'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsNewRoute = AppContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsContractIdIndexRoute =
  AppContractsContractIdIndexRouteImport.update({
    id: '/contracts/$contractId/',
    path: '/contracts/$contractId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdVistoriaImagemRoute =
  AppContractsContractIdVistoriaImagemRouteImport.update({
    id: '/contracts/$contractId/vistoria-imagem',
    path: '/contracts/$contractId/vistoria-imagem',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdTimelineRoute =
  AppContractsContractIdTimelineRouteImport.update({
    id: '/contracts/$contractId/timeline',
    path: '/contracts/$contractId/timeline',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdSubcontratosRoute =
  AppContractsContractIdSubcontratosRouteImport.update({
    id: '/contracts/$contractId/subcontratos',
    path: '/contracts/$contractId/subcontratos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdRmaRoute =
  AppContractsContractIdRmaRouteImport.update({
    id: '/contracts/$contractId/rma',
    path: '/contracts/$contractId/rma',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdPlanoAcaoRoute =
  AppContractsContractIdPlanoAcaoRouteImport.update({
    id: '/contracts/$contractId/plano-acao',
    path: '/contracts/$contractId/plano-acao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdNormalizacaoRoute =
  AppContractsContractIdNormalizacaoRouteImport.update({
    id: '/contracts/$contractId/normalizacao',
    path: '/contracts/$contractId/normalizacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdMelhoriasDocRoute =
  AppContractsContractIdMelhoriasDocRouteImport.update({
    id: '/contracts/$contractId/melhorias-doc',
    path: '/contracts/$contractId/melhorias-doc',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdMapeamentoRoute =
  AppContractsContractIdMapeamentoRouteImport.update({
    id: '/contracts/$contractId/mapeamento',
    path: '/contracts/$contractId/mapeamento',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdMapaRoute =
  AppContractsContractIdMapaRouteImport.update({
    id: '/contracts/$contractId/mapa',
    path: '/contracts/$contractId/mapa',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdExtracaoRoute =
  AppContractsContractIdExtracaoRouteImport.update({
    id: '/contracts/$contractId/extracao',
    path: '/contracts/$contractId/extracao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDashboardRoute =
  AppContractsContractIdDashboardRouteImport.update({
    id: '/contracts/$contractId/dashboard',
    path: '/contracts/$contractId/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdCondutasRoute =
  AppContractsContractIdCondutasRouteImport.update({
    id: '/contracts/$contractId/condutas',
    path: '/contracts/$contractId/condutas',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdChatRoute =
  AppContractsContractIdChatRouteImport.update({
    id: '/contracts/$contractId/chat',
    path: '/contracts/$contractId/chat',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdBibliotecaRoute =
  AppContractsContractIdBibliotecaRouteImport.update({
    id: '/contracts/$contractId/biblioteca',
    path: '/contracts/$contractId/biblioteca',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdRmaIndexRoute =
  AppContractsContractIdRmaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdDesequilibrioIndexRoute =
  AppContractsContractIdDesequilibrioIndexRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/',
    path: '/contracts/$contractId/desequilibrio/',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdControleDocumentalIndexRoute =
  AppContractsContractIdControleDocumentalIndexRouteImport.update({
    id: '/contracts/$contractId/controle-documental/',
    path: '/contracts/$contractId/controle-documental/',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdContabilIndexRoute =
  AppContractsContractIdContabilIndexRouteImport.update({
    id: '/contracts/$contractId/contabil/',
    path: '/contracts/$contractId/contabil/',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdChecklistIndexRoute =
  AppContractsContractIdChecklistIndexRouteImport.update({
    id: '/contracts/$contractId/checklist/',
    path: '/contracts/$contractId/checklist/',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdRmaVisaoGeralRoute =
  AppContractsContractIdRmaVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaResponsabilidadeRoute =
  AppContractsContractIdRmaResponsabilidadeRouteImport.update({
    id: '/responsabilidade',
    path: '/responsabilidade',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaRecursosRoute =
  AppContractsContractIdRmaRecursosRouteImport.update({
    id: '/recursos',
    path: '/recursos',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaProdutividadeRoute =
  AppContractsContractIdRmaProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaPrazoRoute =
  AppContractsContractIdRmaPrazoRouteImport.update({
    id: '/prazo',
    path: '/prazo',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaPlanoAcaoRoute =
  AppContractsContractIdRmaPlanoAcaoRouteImport.update({
    id: '/plano-acao',
    path: '/plano-acao',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaPanoramaRoute =
  AppContractsContractIdRmaPanoramaRouteImport.update({
    id: '/panorama',
    path: '/panorama',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaInsumosRoute =
  AppContractsContractIdRmaInsumosRouteImport.update({
    id: '/insumos',
    path: '/insumos',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaIndicadoresRoute =
  AppContractsContractIdRmaIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaFaturamentoRoute =
  AppContractsContractIdRmaFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaCurvasRoute =
  AppContractsContractIdRmaCurvasRouteImport.update({
    id: '/curvas',
    path: '/curvas',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaCondutasRoute =
  AppContractsContractIdRmaCondutasRouteImport.update({
    id: '/condutas',
    path: '/condutas',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdRmaChuvasRoute =
  AppContractsContractIdRmaChuvasRouteImport.update({
    id: '/chuvas',
    path: '/chuvas',
    getParentRoute: () => AppContractsContractIdRmaRoute,
  } as any)
const AppContractsContractIdPreTranspasseRoute =
  AppContractsContractIdPreTranspasseRouteImport.update({
    id: '/contracts/$contractId/pre/transpasse',
    path: '/contracts/$contractId/pre/transpasse',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdPreRevisaoRoute =
  AppContractsContractIdPreRevisaoRouteImport.update({
    id: '/contracts/$contractId/pre/revisao',
    path: '/contracts/$contractId/pre/revisao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdPreDiagnosticoRoute =
  AppContractsContractIdPreDiagnosticoRouteImport.update({
    id: '/contracts/$contractId/pre/diagnostico',
    path: '/contracts/$contractId/pre/diagnostico',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdPreBasesRoute =
  AppContractsContractIdPreBasesRouteImport.update({
    id: '/contracts/$contractId/pre/bases',
    path: '/contracts/$contractId/pre/bases',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdFinalizacaoPleitosRoute =
  AppContractsContractIdFinalizacaoPleitosRouteImport.update({
    id: '/contracts/$contractId/finalizacao/pleitos',
    path: '/contracts/$contractId/finalizacao/pleitos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdFinalizacaoLicoesRoute =
  AppContractsContractIdFinalizacaoLicoesRouteImport.update({
    id: '/contracts/$contractId/finalizacao/licoes',
    path: '/contracts/$contractId/finalizacao/licoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdFinalizacaoJudicialRoute =
  AppContractsContractIdFinalizacaoJudicialRouteImport.update({
    id: '/contracts/$contractId/finalizacao/judicial',
    path: '/contracts/$contractId/finalizacao/judicial',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioValorAgregadoRoute =
  AppContractsContractIdDesequilibrioValorAgregadoRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/valor-agregado',
    path: '/contracts/$contractId/desequilibrio/valor-agregado',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioPontuaisRoute =
  AppContractsContractIdDesequilibrioPontuaisRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/pontuais',
    path: '/contracts/$contractId/desequilibrio/pontuais',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioInsumosRoute =
  AppContractsContractIdDesequilibrioInsumosRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/insumos',
    path: '/contracts/$contractId/desequilibrio/insumos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioIndiretosRoute =
  AppContractsContractIdDesequilibrioIndiretosRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/indiretos',
    path: '/contracts/$contractId/desequilibrio/indiretos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioGeradorClaimRoute =
  AppContractsContractIdDesequilibrioGeradorClaimRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/gerador-claim',
    path: '/contracts/$contractId/desequilibrio/gerador-claim',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioEncargosRoute =
  AppContractsContractIdDesequilibrioEncargosRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/encargos',
    path: '/contracts/$contractId/desequilibrio/encargos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdDesequilibrioBdiRoute =
  AppContractsContractIdDesequilibrioBdiRouteImport.update({
    id: '/contracts/$contractId/desequilibrio/bdi',
    path: '/contracts/$contractId/desequilibrio/bdi',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdControleDocumentalOperacaoRoute =
  AppContractsContractIdControleDocumentalOperacaoRouteImport.update({
    id: '/contracts/$contractId/controle-documental/operacao',
    path: '/contracts/$contractId/controle-documental/operacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdControleDocumentalDocumentosRoute =
  AppContractsContractIdControleDocumentalDocumentosRouteImport.update({
    id: '/contracts/$contractId/controle-documental/documentos',
    path: '/contracts/$contractId/controle-documental/documentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdControleDocumentalAreasRoute =
  AppContractsContractIdControleDocumentalAreasRouteImport.update({
    id: '/contracts/$contractId/controle-documental/areas',
    path: '/contracts/$contractId/controle-documental/areas',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdContabilPericialRoute =
  AppContractsContractIdContabilPericialRouteImport.update({
    id: '/contracts/$contractId/contabil/pericial',
    path: '/contracts/$contractId/contabil/pericial',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdContabilOperacaoRoute =
  AppContractsContractIdContabilOperacaoRouteImport.update({
    id: '/contracts/$contractId/contabil/operacao',
    path: '/contracts/$contractId/contabil/operacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdContabilCapituloRoute =
  AppContractsContractIdContabilCapituloRouteImport.update({
    id: '/contracts/$contractId/contabil/capitulo',
    path: '/contracts/$contractId/contabil/capitulo',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractsContractIdChecklistSetorRoute =
  AppContractsContractIdChecklistSetorRouteImport.update({
    id: '/contracts/$contractId/checklist/$setor',
    path: '/contracts/$contractId/checklist/$setor',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/contracts/new': typeof AppContractsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/contracts/$contractId/biblioteca': typeof AppContractsContractIdBibliotecaRoute
  '/contracts/$contractId/chat': typeof AppContractsContractIdChatRoute
  '/contracts/$contractId/condutas': typeof AppContractsContractIdCondutasRoute
  '/contracts/$contractId/dashboard': typeof AppContractsContractIdDashboardRoute
  '/contracts/$contractId/extracao': typeof AppContractsContractIdExtracaoRoute
  '/contracts/$contractId/mapa': typeof AppContractsContractIdMapaRoute
  '/contracts/$contractId/mapeamento': typeof AppContractsContractIdMapeamentoRoute
  '/contracts/$contractId/melhorias-doc': typeof AppContractsContractIdMelhoriasDocRoute
  '/contracts/$contractId/normalizacao': typeof AppContractsContractIdNormalizacaoRoute
  '/contracts/$contractId/plano-acao': typeof AppContractsContractIdPlanoAcaoRoute
  '/contracts/$contractId/rma': typeof AppContractsContractIdRmaRouteWithChildren
  '/contracts/$contractId/subcontratos': typeof AppContractsContractIdSubcontratosRoute
  '/contracts/$contractId/timeline': typeof AppContractsContractIdTimelineRoute
  '/contracts/$contractId/vistoria-imagem': typeof AppContractsContractIdVistoriaImagemRoute
  '/contracts/$contractId/': typeof AppContractsContractIdIndexRoute
  '/contracts/$contractId/checklist/$setor': typeof AppContractsContractIdChecklistSetorRoute
  '/contracts/$contractId/contabil/capitulo': typeof AppContractsContractIdContabilCapituloRoute
  '/contracts/$contractId/contabil/operacao': typeof AppContractsContractIdContabilOperacaoRoute
  '/contracts/$contractId/contabil/pericial': typeof AppContractsContractIdContabilPericialRoute
  '/contracts/$contractId/controle-documental/areas': typeof AppContractsContractIdControleDocumentalAreasRoute
  '/contracts/$contractId/controle-documental/documentos': typeof AppContractsContractIdControleDocumentalDocumentosRoute
  '/contracts/$contractId/controle-documental/operacao': typeof AppContractsContractIdControleDocumentalOperacaoRoute
  '/contracts/$contractId/desequilibrio/bdi': typeof AppContractsContractIdDesequilibrioBdiRoute
  '/contracts/$contractId/desequilibrio/encargos': typeof AppContractsContractIdDesequilibrioEncargosRoute
  '/contracts/$contractId/desequilibrio/gerador-claim': typeof AppContractsContractIdDesequilibrioGeradorClaimRoute
  '/contracts/$contractId/desequilibrio/indiretos': typeof AppContractsContractIdDesequilibrioIndiretosRoute
  '/contracts/$contractId/desequilibrio/insumos': typeof AppContractsContractIdDesequilibrioInsumosRoute
  '/contracts/$contractId/desequilibrio/pontuais': typeof AppContractsContractIdDesequilibrioPontuaisRoute
  '/contracts/$contractId/desequilibrio/valor-agregado': typeof AppContractsContractIdDesequilibrioValorAgregadoRoute
  '/contracts/$contractId/finalizacao/judicial': typeof AppContractsContractIdFinalizacaoJudicialRoute
  '/contracts/$contractId/finalizacao/licoes': typeof AppContractsContractIdFinalizacaoLicoesRoute
  '/contracts/$contractId/finalizacao/pleitos': typeof AppContractsContractIdFinalizacaoPleitosRoute
  '/contracts/$contractId/pre/bases': typeof AppContractsContractIdPreBasesRoute
  '/contracts/$contractId/pre/diagnostico': typeof AppContractsContractIdPreDiagnosticoRoute
  '/contracts/$contractId/pre/revisao': typeof AppContractsContractIdPreRevisaoRoute
  '/contracts/$contractId/pre/transpasse': typeof AppContractsContractIdPreTranspasseRoute
  '/contracts/$contractId/rma/chuvas': typeof AppContractsContractIdRmaChuvasRoute
  '/contracts/$contractId/rma/condutas': typeof AppContractsContractIdRmaCondutasRoute
  '/contracts/$contractId/rma/curvas': typeof AppContractsContractIdRmaCurvasRoute
  '/contracts/$contractId/rma/faturamento': typeof AppContractsContractIdRmaFaturamentoRoute
  '/contracts/$contractId/rma/indicadores': typeof AppContractsContractIdRmaIndicadoresRoute
  '/contracts/$contractId/rma/insumos': typeof AppContractsContractIdRmaInsumosRoute
  '/contracts/$contractId/rma/panorama': typeof AppContractsContractIdRmaPanoramaRoute
  '/contracts/$contractId/rma/plano-acao': typeof AppContractsContractIdRmaPlanoAcaoRoute
  '/contracts/$contractId/rma/prazo': typeof AppContractsContractIdRmaPrazoRoute
  '/contracts/$contractId/rma/produtividade': typeof AppContractsContractIdRmaProdutividadeRoute
  '/contracts/$contractId/rma/recursos': typeof AppContractsContractIdRmaRecursosRoute
  '/contracts/$contractId/rma/responsabilidade': typeof AppContractsContractIdRmaResponsabilidadeRoute
  '/contracts/$contractId/rma/visao-geral': typeof AppContractsContractIdRmaVisaoGeralRoute
  '/contracts/$contractId/checklist/': typeof AppContractsContractIdChecklistIndexRoute
  '/contracts/$contractId/contabil/': typeof AppContractsContractIdContabilIndexRoute
  '/contracts/$contractId/controle-documental/': typeof AppContractsContractIdControleDocumentalIndexRoute
  '/contracts/$contractId/desequilibrio/': typeof AppContractsContractIdDesequilibrioIndexRoute
  '/contracts/$contractId/rma/': typeof AppContractsContractIdRmaIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/contracts/new': typeof AppContractsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/contracts': typeof AppContractsIndexRoute
  '/contracts/$contractId/biblioteca': typeof AppContractsContractIdBibliotecaRoute
  '/contracts/$contractId/chat': typeof AppContractsContractIdChatRoute
  '/contracts/$contractId/condutas': typeof AppContractsContractIdCondutasRoute
  '/contracts/$contractId/dashboard': typeof AppContractsContractIdDashboardRoute
  '/contracts/$contractId/extracao': typeof AppContractsContractIdExtracaoRoute
  '/contracts/$contractId/mapa': typeof AppContractsContractIdMapaRoute
  '/contracts/$contractId/mapeamento': typeof AppContractsContractIdMapeamentoRoute
  '/contracts/$contractId/melhorias-doc': typeof AppContractsContractIdMelhoriasDocRoute
  '/contracts/$contractId/normalizacao': typeof AppContractsContractIdNormalizacaoRoute
  '/contracts/$contractId/plano-acao': typeof AppContractsContractIdPlanoAcaoRoute
  '/contracts/$contractId/subcontratos': typeof AppContractsContractIdSubcontratosRoute
  '/contracts/$contractId/timeline': typeof AppContractsContractIdTimelineRoute
  '/contracts/$contractId/vistoria-imagem': typeof AppContractsContractIdVistoriaImagemRoute
  '/contracts/$contractId': typeof AppContractsContractIdIndexRoute
  '/contracts/$contractId/checklist/$setor': typeof AppContractsContractIdChecklistSetorRoute
  '/contracts/$contractId/contabil/capitulo': typeof AppContractsContractIdContabilCapituloRoute
  '/contracts/$contractId/contabil/operacao': typeof AppContractsContractIdContabilOperacaoRoute
  '/contracts/$contractId/contabil/pericial': typeof AppContractsContractIdContabilPericialRoute
  '/contracts/$contractId/controle-documental/areas': typeof AppContractsContractIdControleDocumentalAreasRoute
  '/contracts/$contractId/controle-documental/documentos': typeof AppContractsContractIdControleDocumentalDocumentosRoute
  '/contracts/$contractId/controle-documental/operacao': typeof AppContractsContractIdControleDocumentalOperacaoRoute
  '/contracts/$contractId/desequilibrio/bdi': typeof AppContractsContractIdDesequilibrioBdiRoute
  '/contracts/$contractId/desequilibrio/encargos': typeof AppContractsContractIdDesequilibrioEncargosRoute
  '/contracts/$contractId/desequilibrio/gerador-claim': typeof AppContractsContractIdDesequilibrioGeradorClaimRoute
  '/contracts/$contractId/desequilibrio/indiretos': typeof AppContractsContractIdDesequilibrioIndiretosRoute
  '/contracts/$contractId/desequilibrio/insumos': typeof AppContractsContractIdDesequilibrioInsumosRoute
  '/contracts/$contractId/desequilibrio/pontuais': typeof AppContractsContractIdDesequilibrioPontuaisRoute
  '/contracts/$contractId/desequilibrio/valor-agregado': typeof AppContractsContractIdDesequilibrioValorAgregadoRoute
  '/contracts/$contractId/finalizacao/judicial': typeof AppContractsContractIdFinalizacaoJudicialRoute
  '/contracts/$contractId/finalizacao/licoes': typeof AppContractsContractIdFinalizacaoLicoesRoute
  '/contracts/$contractId/finalizacao/pleitos': typeof AppContractsContractIdFinalizacaoPleitosRoute
  '/contracts/$contractId/pre/bases': typeof AppContractsContractIdPreBasesRoute
  '/contracts/$contractId/pre/diagnostico': typeof AppContractsContractIdPreDiagnosticoRoute
  '/contracts/$contractId/pre/revisao': typeof AppContractsContractIdPreRevisaoRoute
  '/contracts/$contractId/pre/transpasse': typeof AppContractsContractIdPreTranspasseRoute
  '/contracts/$contractId/rma/chuvas': typeof AppContractsContractIdRmaChuvasRoute
  '/contracts/$contractId/rma/condutas': typeof AppContractsContractIdRmaCondutasRoute
  '/contracts/$contractId/rma/curvas': typeof AppContractsContractIdRmaCurvasRoute
  '/contracts/$contractId/rma/faturamento': typeof AppContractsContractIdRmaFaturamentoRoute
  '/contracts/$contractId/rma/indicadores': typeof AppContractsContractIdRmaIndicadoresRoute
  '/contracts/$contractId/rma/insumos': typeof AppContractsContractIdRmaInsumosRoute
  '/contracts/$contractId/rma/panorama': typeof AppContractsContractIdRmaPanoramaRoute
  '/contracts/$contractId/rma/plano-acao': typeof AppContractsContractIdRmaPlanoAcaoRoute
  '/contracts/$contractId/rma/prazo': typeof AppContractsContractIdRmaPrazoRoute
  '/contracts/$contractId/rma/produtividade': typeof AppContractsContractIdRmaProdutividadeRoute
  '/contracts/$contractId/rma/recursos': typeof AppContractsContractIdRmaRecursosRoute
  '/contracts/$contractId/rma/responsabilidade': typeof AppContractsContractIdRmaResponsabilidadeRoute
  '/contracts/$contractId/rma/visao-geral': typeof AppContractsContractIdRmaVisaoGeralRoute
  '/contracts/$contractId/checklist': typeof AppContractsContractIdChecklistIndexRoute
  '/contracts/$contractId/contabil': typeof AppContractsContractIdContabilIndexRoute
  '/contracts/$contractId/controle-documental': typeof AppContractsContractIdControleDocumentalIndexRoute
  '/contracts/$contractId/desequilibrio': typeof AppContractsContractIdDesequilibrioIndexRoute
  '/contracts/$contractId/rma': typeof AppContractsContractIdRmaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/contracts/new': typeof AppContractsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/contracts/$contractId/biblioteca': typeof AppContractsContractIdBibliotecaRoute
  '/_app/contracts/$contractId/chat': typeof AppContractsContractIdChatRoute
  '/_app/contracts/$contractId/condutas': typeof AppContractsContractIdCondutasRoute
  '/_app/contracts/$contractId/dashboard': typeof AppContractsContractIdDashboardRoute
  '/_app/contracts/$contractId/extracao': typeof AppContractsContractIdExtracaoRoute
  '/_app/contracts/$contractId/mapa': typeof AppContractsContractIdMapaRoute
  '/_app/contracts/$contractId/mapeamento': typeof AppContractsContractIdMapeamentoRoute
  '/_app/contracts/$contractId/melhorias-doc': typeof AppContractsContractIdMelhoriasDocRoute
  '/_app/contracts/$contractId/normalizacao': typeof AppContractsContractIdNormalizacaoRoute
  '/_app/contracts/$contractId/plano-acao': typeof AppContractsContractIdPlanoAcaoRoute
  '/_app/contracts/$contractId/rma': typeof AppContractsContractIdRmaRouteWithChildren
  '/_app/contracts/$contractId/subcontratos': typeof AppContractsContractIdSubcontratosRoute
  '/_app/contracts/$contractId/timeline': typeof AppContractsContractIdTimelineRoute
  '/_app/contracts/$contractId/vistoria-imagem': typeof AppContractsContractIdVistoriaImagemRoute
  '/_app/contracts/$contractId/': typeof AppContractsContractIdIndexRoute
  '/_app/contracts/$contractId/checklist/$setor': typeof AppContractsContractIdChecklistSetorRoute
  '/_app/contracts/$contractId/contabil/capitulo': typeof AppContractsContractIdContabilCapituloRoute
  '/_app/contracts/$contractId/contabil/operacao': typeof AppContractsContractIdContabilOperacaoRoute
  '/_app/contracts/$contractId/contabil/pericial': typeof AppContractsContractIdContabilPericialRoute
  '/_app/contracts/$contractId/controle-documental/areas': typeof AppContractsContractIdControleDocumentalAreasRoute
  '/_app/contracts/$contractId/controle-documental/documentos': typeof AppContractsContractIdControleDocumentalDocumentosRoute
  '/_app/contracts/$contractId/controle-documental/operacao': typeof AppContractsContractIdControleDocumentalOperacaoRoute
  '/_app/contracts/$contractId/desequilibrio/bdi': typeof AppContractsContractIdDesequilibrioBdiRoute
  '/_app/contracts/$contractId/desequilibrio/encargos': typeof AppContractsContractIdDesequilibrioEncargosRoute
  '/_app/contracts/$contractId/desequilibrio/gerador-claim': typeof AppContractsContractIdDesequilibrioGeradorClaimRoute
  '/_app/contracts/$contractId/desequilibrio/indiretos': typeof AppContractsContractIdDesequilibrioIndiretosRoute
  '/_app/contracts/$contractId/desequilibrio/insumos': typeof AppContractsContractIdDesequilibrioInsumosRoute
  '/_app/contracts/$contractId/desequilibrio/pontuais': typeof AppContractsContractIdDesequilibrioPontuaisRoute
  '/_app/contracts/$contractId/desequilibrio/valor-agregado': typeof AppContractsContractIdDesequilibrioValorAgregadoRoute
  '/_app/contracts/$contractId/finalizacao/judicial': typeof AppContractsContractIdFinalizacaoJudicialRoute
  '/_app/contracts/$contractId/finalizacao/licoes': typeof AppContractsContractIdFinalizacaoLicoesRoute
  '/_app/contracts/$contractId/finalizacao/pleitos': typeof AppContractsContractIdFinalizacaoPleitosRoute
  '/_app/contracts/$contractId/pre/bases': typeof AppContractsContractIdPreBasesRoute
  '/_app/contracts/$contractId/pre/diagnostico': typeof AppContractsContractIdPreDiagnosticoRoute
  '/_app/contracts/$contractId/pre/revisao': typeof AppContractsContractIdPreRevisaoRoute
  '/_app/contracts/$contractId/pre/transpasse': typeof AppContractsContractIdPreTranspasseRoute
  '/_app/contracts/$contractId/rma/chuvas': typeof AppContractsContractIdRmaChuvasRoute
  '/_app/contracts/$contractId/rma/condutas': typeof AppContractsContractIdRmaCondutasRoute
  '/_app/contracts/$contractId/rma/curvas': typeof AppContractsContractIdRmaCurvasRoute
  '/_app/contracts/$contractId/rma/faturamento': typeof AppContractsContractIdRmaFaturamentoRoute
  '/_app/contracts/$contractId/rma/indicadores': typeof AppContractsContractIdRmaIndicadoresRoute
  '/_app/contracts/$contractId/rma/insumos': typeof AppContractsContractIdRmaInsumosRoute
  '/_app/contracts/$contractId/rma/panorama': typeof AppContractsContractIdRmaPanoramaRoute
  '/_app/contracts/$contractId/rma/plano-acao': typeof AppContractsContractIdRmaPlanoAcaoRoute
  '/_app/contracts/$contractId/rma/prazo': typeof AppContractsContractIdRmaPrazoRoute
  '/_app/contracts/$contractId/rma/produtividade': typeof AppContractsContractIdRmaProdutividadeRoute
  '/_app/contracts/$contractId/rma/recursos': typeof AppContractsContractIdRmaRecursosRoute
  '/_app/contracts/$contractId/rma/responsabilidade': typeof AppContractsContractIdRmaResponsabilidadeRoute
  '/_app/contracts/$contractId/rma/visao-geral': typeof AppContractsContractIdRmaVisaoGeralRoute
  '/_app/contracts/$contractId/checklist/': typeof AppContractsContractIdChecklistIndexRoute
  '/_app/contracts/$contractId/contabil/': typeof AppContractsContractIdContabilIndexRoute
  '/_app/contracts/$contractId/controle-documental/': typeof AppContractsContractIdControleDocumentalIndexRoute
  '/_app/contracts/$contractId/desequilibrio/': typeof AppContractsContractIdDesequilibrioIndexRoute
  '/_app/contracts/$contractId/rma/': typeof AppContractsContractIdRmaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/login'
    | '/settings'
    | '/admin/audit'
    | '/admin/users'
    | '/contracts/new'
    | '/admin/'
    | '/contracts/'
    | '/contracts/$contractId/biblioteca'
    | '/contracts/$contractId/chat'
    | '/contracts/$contractId/condutas'
    | '/contracts/$contractId/dashboard'
    | '/contracts/$contractId/extracao'
    | '/contracts/$contractId/mapa'
    | '/contracts/$contractId/mapeamento'
    | '/contracts/$contractId/melhorias-doc'
    | '/contracts/$contractId/normalizacao'
    | '/contracts/$contractId/plano-acao'
    | '/contracts/$contractId/rma'
    | '/contracts/$contractId/subcontratos'
    | '/contracts/$contractId/timeline'
    | '/contracts/$contractId/vistoria-imagem'
    | '/contracts/$contractId/'
    | '/contracts/$contractId/checklist/$setor'
    | '/contracts/$contractId/contabil/capitulo'
    | '/contracts/$contractId/contabil/operacao'
    | '/contracts/$contractId/contabil/pericial'
    | '/contracts/$contractId/controle-documental/areas'
    | '/contracts/$contractId/controle-documental/documentos'
    | '/contracts/$contractId/controle-documental/operacao'
    | '/contracts/$contractId/desequilibrio/bdi'
    | '/contracts/$contractId/desequilibrio/encargos'
    | '/contracts/$contractId/desequilibrio/gerador-claim'
    | '/contracts/$contractId/desequilibrio/indiretos'
    | '/contracts/$contractId/desequilibrio/insumos'
    | '/contracts/$contractId/desequilibrio/pontuais'
    | '/contracts/$contractId/desequilibrio/valor-agregado'
    | '/contracts/$contractId/finalizacao/judicial'
    | '/contracts/$contractId/finalizacao/licoes'
    | '/contracts/$contractId/finalizacao/pleitos'
    | '/contracts/$contractId/pre/bases'
    | '/contracts/$contractId/pre/diagnostico'
    | '/contracts/$contractId/pre/revisao'
    | '/contracts/$contractId/pre/transpasse'
    | '/contracts/$contractId/rma/chuvas'
    | '/contracts/$contractId/rma/condutas'
    | '/contracts/$contractId/rma/curvas'
    | '/contracts/$contractId/rma/faturamento'
    | '/contracts/$contractId/rma/indicadores'
    | '/contracts/$contractId/rma/insumos'
    | '/contracts/$contractId/rma/panorama'
    | '/contracts/$contractId/rma/plano-acao'
    | '/contracts/$contractId/rma/prazo'
    | '/contracts/$contractId/rma/produtividade'
    | '/contracts/$contractId/rma/recursos'
    | '/contracts/$contractId/rma/responsabilidade'
    | '/contracts/$contractId/rma/visao-geral'
    | '/contracts/$contractId/checklist/'
    | '/contracts/$contractId/contabil/'
    | '/contracts/$contractId/controle-documental/'
    | '/contracts/$contractId/desequilibrio/'
    | '/contracts/$contractId/rma/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/login'
    | '/settings'
    | '/'
    | '/admin/audit'
    | '/admin/users'
    | '/contracts/new'
    | '/admin'
    | '/contracts'
    | '/contracts/$contractId/biblioteca'
    | '/contracts/$contractId/chat'
    | '/contracts/$contractId/condutas'
    | '/contracts/$contractId/dashboard'
    | '/contracts/$contractId/extracao'
    | '/contracts/$contractId/mapa'
    | '/contracts/$contractId/mapeamento'
    | '/contracts/$contractId/melhorias-doc'
    | '/contracts/$contractId/normalizacao'
    | '/contracts/$contractId/plano-acao'
    | '/contracts/$contractId/subcontratos'
    | '/contracts/$contractId/timeline'
    | '/contracts/$contractId/vistoria-imagem'
    | '/contracts/$contractId'
    | '/contracts/$contractId/checklist/$setor'
    | '/contracts/$contractId/contabil/capitulo'
    | '/contracts/$contractId/contabil/operacao'
    | '/contracts/$contractId/contabil/pericial'
    | '/contracts/$contractId/controle-documental/areas'
    | '/contracts/$contractId/controle-documental/documentos'
    | '/contracts/$contractId/controle-documental/operacao'
    | '/contracts/$contractId/desequilibrio/bdi'
    | '/contracts/$contractId/desequilibrio/encargos'
    | '/contracts/$contractId/desequilibrio/gerador-claim'
    | '/contracts/$contractId/desequilibrio/indiretos'
    | '/contracts/$contractId/desequilibrio/insumos'
    | '/contracts/$contractId/desequilibrio/pontuais'
    | '/contracts/$contractId/desequilibrio/valor-agregado'
    | '/contracts/$contractId/finalizacao/judicial'
    | '/contracts/$contractId/finalizacao/licoes'
    | '/contracts/$contractId/finalizacao/pleitos'
    | '/contracts/$contractId/pre/bases'
    | '/contracts/$contractId/pre/diagnostico'
    | '/contracts/$contractId/pre/revisao'
    | '/contracts/$contractId/pre/transpasse'
    | '/contracts/$contractId/rma/chuvas'
    | '/contracts/$contractId/rma/condutas'
    | '/contracts/$contractId/rma/curvas'
    | '/contracts/$contractId/rma/faturamento'
    | '/contracts/$contractId/rma/indicadores'
    | '/contracts/$contractId/rma/insumos'
    | '/contracts/$contractId/rma/panorama'
    | '/contracts/$contractId/rma/plano-acao'
    | '/contracts/$contractId/rma/prazo'
    | '/contracts/$contractId/rma/produtividade'
    | '/contracts/$contractId/rma/recursos'
    | '/contracts/$contractId/rma/responsabilidade'
    | '/contracts/$contractId/rma/visao-geral'
    | '/contracts/$contractId/checklist'
    | '/contracts/$contractId/contabil'
    | '/contracts/$contractId/controle-documental'
    | '/contracts/$contractId/desequilibrio'
    | '/contracts/$contractId/rma'
  id:
    | '__root__'
    | '/_app'
    | '/design-system'
    | '/login'
    | '/_app/settings'
    | '/_app/'
    | '/_app/admin/audit'
    | '/_app/admin/users'
    | '/_app/contracts/new'
    | '/_app/admin/'
    | '/_app/contracts/'
    | '/_app/contracts/$contractId/biblioteca'
    | '/_app/contracts/$contractId/chat'
    | '/_app/contracts/$contractId/condutas'
    | '/_app/contracts/$contractId/dashboard'
    | '/_app/contracts/$contractId/extracao'
    | '/_app/contracts/$contractId/mapa'
    | '/_app/contracts/$contractId/mapeamento'
    | '/_app/contracts/$contractId/melhorias-doc'
    | '/_app/contracts/$contractId/normalizacao'
    | '/_app/contracts/$contractId/plano-acao'
    | '/_app/contracts/$contractId/rma'
    | '/_app/contracts/$contractId/subcontratos'
    | '/_app/contracts/$contractId/timeline'
    | '/_app/contracts/$contractId/vistoria-imagem'
    | '/_app/contracts/$contractId/'
    | '/_app/contracts/$contractId/checklist/$setor'
    | '/_app/contracts/$contractId/contabil/capitulo'
    | '/_app/contracts/$contractId/contabil/operacao'
    | '/_app/contracts/$contractId/contabil/pericial'
    | '/_app/contracts/$contractId/controle-documental/areas'
    | '/_app/contracts/$contractId/controle-documental/documentos'
    | '/_app/contracts/$contractId/controle-documental/operacao'
    | '/_app/contracts/$contractId/desequilibrio/bdi'
    | '/_app/contracts/$contractId/desequilibrio/encargos'
    | '/_app/contracts/$contractId/desequilibrio/gerador-claim'
    | '/_app/contracts/$contractId/desequilibrio/indiretos'
    | '/_app/contracts/$contractId/desequilibrio/insumos'
    | '/_app/contracts/$contractId/desequilibrio/pontuais'
    | '/_app/contracts/$contractId/desequilibrio/valor-agregado'
    | '/_app/contracts/$contractId/finalizacao/judicial'
    | '/_app/contracts/$contractId/finalizacao/licoes'
    | '/_app/contracts/$contractId/finalizacao/pleitos'
    | '/_app/contracts/$contractId/pre/bases'
    | '/_app/contracts/$contractId/pre/diagnostico'
    | '/_app/contracts/$contractId/pre/revisao'
    | '/_app/contracts/$contractId/pre/transpasse'
    | '/_app/contracts/$contractId/rma/chuvas'
    | '/_app/contracts/$contractId/rma/condutas'
    | '/_app/contracts/$contractId/rma/curvas'
    | '/_app/contracts/$contractId/rma/faturamento'
    | '/_app/contracts/$contractId/rma/indicadores'
    | '/_app/contracts/$contractId/rma/insumos'
    | '/_app/contracts/$contractId/rma/panorama'
    | '/_app/contracts/$contractId/rma/plano-acao'
    | '/_app/contracts/$contractId/rma/prazo'
    | '/_app/contracts/$contractId/rma/produtividade'
    | '/_app/contracts/$contractId/rma/recursos'
    | '/_app/contracts/$contractId/rma/responsabilidade'
    | '/_app/contracts/$contractId/rma/visao-geral'
    | '/_app/contracts/$contractId/checklist/'
    | '/_app/contracts/$contractId/contabil/'
    | '/_app/contracts/$contractId/controle-documental/'
    | '/_app/contracts/$contractId/desequilibrio/'
    | '/_app/contracts/$contractId/rma/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/new': {
      id: '/_app/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AppContractsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/': {
      id: '/_app/contracts/$contractId/'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId/'
      preLoaderRoute: typeof AppContractsContractIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/vistoria-imagem': {
      id: '/_app/contracts/$contractId/vistoria-imagem'
      path: '/contracts/$contractId/vistoria-imagem'
      fullPath: '/contracts/$contractId/vistoria-imagem'
      preLoaderRoute: typeof AppContractsContractIdVistoriaImagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/timeline': {
      id: '/_app/contracts/$contractId/timeline'
      path: '/contracts/$contractId/timeline'
      fullPath: '/contracts/$contractId/timeline'
      preLoaderRoute: typeof AppContractsContractIdTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/subcontratos': {
      id: '/_app/contracts/$contractId/subcontratos'
      path: '/contracts/$contractId/subcontratos'
      fullPath: '/contracts/$contractId/subcontratos'
      preLoaderRoute: typeof AppContractsContractIdSubcontratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/rma': {
      id: '/_app/contracts/$contractId/rma'
      path: '/contracts/$contractId/rma'
      fullPath: '/contracts/$contractId/rma'
      preLoaderRoute: typeof AppContractsContractIdRmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/plano-acao': {
      id: '/_app/contracts/$contractId/plano-acao'
      path: '/contracts/$contractId/plano-acao'
      fullPath: '/contracts/$contractId/plano-acao'
      preLoaderRoute: typeof AppContractsContractIdPlanoAcaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/normalizacao': {
      id: '/_app/contracts/$contractId/normalizacao'
      path: '/contracts/$contractId/normalizacao'
      fullPath: '/contracts/$contractId/normalizacao'
      preLoaderRoute: typeof AppContractsContractIdNormalizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/melhorias-doc': {
      id: '/_app/contracts/$contractId/melhorias-doc'
      path: '/contracts/$contractId/melhorias-doc'
      fullPath: '/contracts/$contractId/melhorias-doc'
      preLoaderRoute: typeof AppContractsContractIdMelhoriasDocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/mapeamento': {
      id: '/_app/contracts/$contractId/mapeamento'
      path: '/contracts/$contractId/mapeamento'
      fullPath: '/contracts/$contractId/mapeamento'
      preLoaderRoute: typeof AppContractsContractIdMapeamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/mapa': {
      id: '/_app/contracts/$contractId/mapa'
      path: '/contracts/$contractId/mapa'
      fullPath: '/contracts/$contractId/mapa'
      preLoaderRoute: typeof AppContractsContractIdMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/extracao': {
      id: '/_app/contracts/$contractId/extracao'
      path: '/contracts/$contractId/extracao'
      fullPath: '/contracts/$contractId/extracao'
      preLoaderRoute: typeof AppContractsContractIdExtracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/dashboard': {
      id: '/_app/contracts/$contractId/dashboard'
      path: '/contracts/$contractId/dashboard'
      fullPath: '/contracts/$contractId/dashboard'
      preLoaderRoute: typeof AppContractsContractIdDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/condutas': {
      id: '/_app/contracts/$contractId/condutas'
      path: '/contracts/$contractId/condutas'
      fullPath: '/contracts/$contractId/condutas'
      preLoaderRoute: typeof AppContractsContractIdCondutasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/chat': {
      id: '/_app/contracts/$contractId/chat'
      path: '/contracts/$contractId/chat'
      fullPath: '/contracts/$contractId/chat'
      preLoaderRoute: typeof AppContractsContractIdChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/biblioteca': {
      id: '/_app/contracts/$contractId/biblioteca'
      path: '/contracts/$contractId/biblioteca'
      fullPath: '/contracts/$contractId/biblioteca'
      preLoaderRoute: typeof AppContractsContractIdBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/rma/': {
      id: '/_app/contracts/$contractId/rma/'
      path: '/'
      fullPath: '/contracts/$contractId/rma/'
      preLoaderRoute: typeof AppContractsContractIdRmaIndexRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/desequilibrio/': {
      id: '/_app/contracts/$contractId/desequilibrio/'
      path: '/contracts/$contractId/desequilibrio'
      fullPath: '/contracts/$contractId/desequilibrio/'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/controle-documental/': {
      id: '/_app/contracts/$contractId/controle-documental/'
      path: '/contracts/$contractId/controle-documental'
      fullPath: '/contracts/$contractId/controle-documental/'
      preLoaderRoute: typeof AppContractsContractIdControleDocumentalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/contabil/': {
      id: '/_app/contracts/$contractId/contabil/'
      path: '/contracts/$contractId/contabil'
      fullPath: '/contracts/$contractId/contabil/'
      preLoaderRoute: typeof AppContractsContractIdContabilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/checklist/': {
      id: '/_app/contracts/$contractId/checklist/'
      path: '/contracts/$contractId/checklist'
      fullPath: '/contracts/$contractId/checklist/'
      preLoaderRoute: typeof AppContractsContractIdChecklistIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/rma/visao-geral': {
      id: '/_app/contracts/$contractId/rma/visao-geral'
      path: '/visao-geral'
      fullPath: '/contracts/$contractId/rma/visao-geral'
      preLoaderRoute: typeof AppContractsContractIdRmaVisaoGeralRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/responsabilidade': {
      id: '/_app/contracts/$contractId/rma/responsabilidade'
      path: '/responsabilidade'
      fullPath: '/contracts/$contractId/rma/responsabilidade'
      preLoaderRoute: typeof AppContractsContractIdRmaResponsabilidadeRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/recursos': {
      id: '/_app/contracts/$contractId/rma/recursos'
      path: '/recursos'
      fullPath: '/contracts/$contractId/rma/recursos'
      preLoaderRoute: typeof AppContractsContractIdRmaRecursosRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/produtividade': {
      id: '/_app/contracts/$contractId/rma/produtividade'
      path: '/produtividade'
      fullPath: '/contracts/$contractId/rma/produtividade'
      preLoaderRoute: typeof AppContractsContractIdRmaProdutividadeRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/prazo': {
      id: '/_app/contracts/$contractId/rma/prazo'
      path: '/prazo'
      fullPath: '/contracts/$contractId/rma/prazo'
      preLoaderRoute: typeof AppContractsContractIdRmaPrazoRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/plano-acao': {
      id: '/_app/contracts/$contractId/rma/plano-acao'
      path: '/plano-acao'
      fullPath: '/contracts/$contractId/rma/plano-acao'
      preLoaderRoute: typeof AppContractsContractIdRmaPlanoAcaoRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/panorama': {
      id: '/_app/contracts/$contractId/rma/panorama'
      path: '/panorama'
      fullPath: '/contracts/$contractId/rma/panorama'
      preLoaderRoute: typeof AppContractsContractIdRmaPanoramaRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/insumos': {
      id: '/_app/contracts/$contractId/rma/insumos'
      path: '/insumos'
      fullPath: '/contracts/$contractId/rma/insumos'
      preLoaderRoute: typeof AppContractsContractIdRmaInsumosRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/indicadores': {
      id: '/_app/contracts/$contractId/rma/indicadores'
      path: '/indicadores'
      fullPath: '/contracts/$contractId/rma/indicadores'
      preLoaderRoute: typeof AppContractsContractIdRmaIndicadoresRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/faturamento': {
      id: '/_app/contracts/$contractId/rma/faturamento'
      path: '/faturamento'
      fullPath: '/contracts/$contractId/rma/faturamento'
      preLoaderRoute: typeof AppContractsContractIdRmaFaturamentoRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/curvas': {
      id: '/_app/contracts/$contractId/rma/curvas'
      path: '/curvas'
      fullPath: '/contracts/$contractId/rma/curvas'
      preLoaderRoute: typeof AppContractsContractIdRmaCurvasRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/condutas': {
      id: '/_app/contracts/$contractId/rma/condutas'
      path: '/condutas'
      fullPath: '/contracts/$contractId/rma/condutas'
      preLoaderRoute: typeof AppContractsContractIdRmaCondutasRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/rma/chuvas': {
      id: '/_app/contracts/$contractId/rma/chuvas'
      path: '/chuvas'
      fullPath: '/contracts/$contractId/rma/chuvas'
      preLoaderRoute: typeof AppContractsContractIdRmaChuvasRouteImport
      parentRoute: typeof AppContractsContractIdRmaRoute
    }
    '/_app/contracts/$contractId/pre/transpasse': {
      id: '/_app/contracts/$contractId/pre/transpasse'
      path: '/contracts/$contractId/pre/transpasse'
      fullPath: '/contracts/$contractId/pre/transpasse'
      preLoaderRoute: typeof AppContractsContractIdPreTranspasseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/pre/revisao': {
      id: '/_app/contracts/$contractId/pre/revisao'
      path: '/contracts/$contractId/pre/revisao'
      fullPath: '/contracts/$contractId/pre/revisao'
      preLoaderRoute: typeof AppContractsContractIdPreRevisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/pre/diagnostico': {
      id: '/_app/contracts/$contractId/pre/diagnostico'
      path: '/contracts/$contractId/pre/diagnostico'
      fullPath: '/contracts/$contractId/pre/diagnostico'
      preLoaderRoute: typeof AppContractsContractIdPreDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/pre/bases': {
      id: '/_app/contracts/$contractId/pre/bases'
      path: '/contracts/$contractId/pre/bases'
      fullPath: '/contracts/$contractId/pre/bases'
      preLoaderRoute: typeof AppContractsContractIdPreBasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/finalizacao/pleitos': {
      id: '/_app/contracts/$contractId/finalizacao/pleitos'
      path: '/contracts/$contractId/finalizacao/pleitos'
      fullPath: '/contracts/$contractId/finalizacao/pleitos'
      preLoaderRoute: typeof AppContractsContractIdFinalizacaoPleitosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/finalizacao/licoes': {
      id: '/_app/contracts/$contractId/finalizacao/licoes'
      path: '/contracts/$contractId/finalizacao/licoes'
      fullPath: '/contracts/$contractId/finalizacao/licoes'
      preLoaderRoute: typeof AppContractsContractIdFinalizacaoLicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/finalizacao/judicial': {
      id: '/_app/contracts/$contractId/finalizacao/judicial'
      path: '/contracts/$contractId/finalizacao/judicial'
      fullPath: '/contracts/$contractId/finalizacao/judicial'
      preLoaderRoute: typeof AppContractsContractIdFinalizacaoJudicialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/valor-agregado': {
      id: '/_app/contracts/$contractId/desequilibrio/valor-agregado'
      path: '/contracts/$contractId/desequilibrio/valor-agregado'
      fullPath: '/contracts/$contractId/desequilibrio/valor-agregado'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioValorAgregadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/pontuais': {
      id: '/_app/contracts/$contractId/desequilibrio/pontuais'
      path: '/contracts/$contractId/desequilibrio/pontuais'
      fullPath: '/contracts/$contractId/desequilibrio/pontuais'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioPontuaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/insumos': {
      id: '/_app/contracts/$contractId/desequilibrio/insumos'
      path: '/contracts/$contractId/desequilibrio/insumos'
      fullPath: '/contracts/$contractId/desequilibrio/insumos'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioInsumosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/indiretos': {
      id: '/_app/contracts/$contractId/desequilibrio/indiretos'
      path: '/contracts/$contractId/desequilibrio/indiretos'
      fullPath: '/contracts/$contractId/desequilibrio/indiretos'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioIndiretosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/gerador-claim': {
      id: '/_app/contracts/$contractId/desequilibrio/gerador-claim'
      path: '/contracts/$contractId/desequilibrio/gerador-claim'
      fullPath: '/contracts/$contractId/desequilibrio/gerador-claim'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioGeradorClaimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/encargos': {
      id: '/_app/contracts/$contractId/desequilibrio/encargos'
      path: '/contracts/$contractId/desequilibrio/encargos'
      fullPath: '/contracts/$contractId/desequilibrio/encargos'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioEncargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/desequilibrio/bdi': {
      id: '/_app/contracts/$contractId/desequilibrio/bdi'
      path: '/contracts/$contractId/desequilibrio/bdi'
      fullPath: '/contracts/$contractId/desequilibrio/bdi'
      preLoaderRoute: typeof AppContractsContractIdDesequilibrioBdiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/controle-documental/operacao': {
      id: '/_app/contracts/$contractId/controle-documental/operacao'
      path: '/contracts/$contractId/controle-documental/operacao'
      fullPath: '/contracts/$contractId/controle-documental/operacao'
      preLoaderRoute: typeof AppContractsContractIdControleDocumentalOperacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/controle-documental/documentos': {
      id: '/_app/contracts/$contractId/controle-documental/documentos'
      path: '/contracts/$contractId/controle-documental/documentos'
      fullPath: '/contracts/$contractId/controle-documental/documentos'
      preLoaderRoute: typeof AppContractsContractIdControleDocumentalDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/controle-documental/areas': {
      id: '/_app/contracts/$contractId/controle-documental/areas'
      path: '/contracts/$contractId/controle-documental/areas'
      fullPath: '/contracts/$contractId/controle-documental/areas'
      preLoaderRoute: typeof AppContractsContractIdControleDocumentalAreasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/contabil/pericial': {
      id: '/_app/contracts/$contractId/contabil/pericial'
      path: '/contracts/$contractId/contabil/pericial'
      fullPath: '/contracts/$contractId/contabil/pericial'
      preLoaderRoute: typeof AppContractsContractIdContabilPericialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/contabil/operacao': {
      id: '/_app/contracts/$contractId/contabil/operacao'
      path: '/contracts/$contractId/contabil/operacao'
      fullPath: '/contracts/$contractId/contabil/operacao'
      preLoaderRoute: typeof AppContractsContractIdContabilOperacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/contabil/capitulo': {
      id: '/_app/contracts/$contractId/contabil/capitulo'
      path: '/contracts/$contractId/contabil/capitulo'
      fullPath: '/contracts/$contractId/contabil/capitulo'
      preLoaderRoute: typeof AppContractsContractIdContabilCapituloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId/checklist/$setor': {
      id: '/_app/contracts/$contractId/checklist/$setor'
      path: '/contracts/$contractId/checklist/$setor'
      fullPath: '/contracts/$contractId/checklist/$setor'
      preLoaderRoute: typeof AppContractsContractIdChecklistSetorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppContractsContractIdRmaRouteChildren {
  AppContractsContractIdRmaChuvasRoute: typeof AppContractsContractIdRmaChuvasRoute
  AppContractsContractIdRmaCondutasRoute: typeof AppContractsContractIdRmaCondutasRoute
  AppContractsContractIdRmaCurvasRoute: typeof AppContractsContractIdRmaCurvasRoute
  AppContractsContractIdRmaFaturamentoRoute: typeof AppContractsContractIdRmaFaturamentoRoute
  AppContractsContractIdRmaIndicadoresRoute: typeof AppContractsContractIdRmaIndicadoresRoute
  AppContractsContractIdRmaInsumosRoute: typeof AppContractsContractIdRmaInsumosRoute
  AppContractsContractIdRmaPanoramaRoute: typeof AppContractsContractIdRmaPanoramaRoute
  AppContractsContractIdRmaPlanoAcaoRoute: typeof AppContractsContractIdRmaPlanoAcaoRoute
  AppContractsContractIdRmaPrazoRoute: typeof AppContractsContractIdRmaPrazoRoute
  AppContractsContractIdRmaProdutividadeRoute: typeof AppContractsContractIdRmaProdutividadeRoute
  AppContractsContractIdRmaRecursosRoute: typeof AppContractsContractIdRmaRecursosRoute
  AppContractsContractIdRmaResponsabilidadeRoute: typeof AppContractsContractIdRmaResponsabilidadeRoute
  AppContractsContractIdRmaVisaoGeralRoute: typeof AppContractsContractIdRmaVisaoGeralRoute
  AppContractsContractIdRmaIndexRoute: typeof AppContractsContractIdRmaIndexRoute
}

const AppContractsContractIdRmaRouteChildren: AppContractsContractIdRmaRouteChildren =
  {
    AppContractsContractIdRmaChuvasRoute: AppContractsContractIdRmaChuvasRoute,
    AppContractsContractIdRmaCondutasRoute:
      AppContractsContractIdRmaCondutasRoute,
    AppContractsContractIdRmaCurvasRoute: AppContractsContractIdRmaCurvasRoute,
    AppContractsContractIdRmaFaturamentoRoute:
      AppContractsContractIdRmaFaturamentoRoute,
    AppContractsContractIdRmaIndicadoresRoute:
      AppContractsContractIdRmaIndicadoresRoute,
    AppContractsContractIdRmaInsumosRoute:
      AppContractsContractIdRmaInsumosRoute,
    AppContractsContractIdRmaPanoramaRoute:
      AppContractsContractIdRmaPanoramaRoute,
    AppContractsContractIdRmaPlanoAcaoRoute:
      AppContractsContractIdRmaPlanoAcaoRoute,
    AppContractsContractIdRmaPrazoRoute: AppContractsContractIdRmaPrazoRoute,
    AppContractsContractIdRmaProdutividadeRoute:
      AppContractsContractIdRmaProdutividadeRoute,
    AppContractsContractIdRmaRecursosRoute:
      AppContractsContractIdRmaRecursosRoute,
    AppContractsContractIdRmaResponsabilidadeRoute:
      AppContractsContractIdRmaResponsabilidadeRoute,
    AppContractsContractIdRmaVisaoGeralRoute:
      AppContractsContractIdRmaVisaoGeralRoute,
    AppContractsContractIdRmaIndexRoute: AppContractsContractIdRmaIndexRoute,
  }

const AppContractsContractIdRmaRouteWithChildren =
  AppContractsContractIdRmaRoute._addFileChildren(
    AppContractsContractIdRmaRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppContractsNewRoute: typeof AppContractsNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppContractsContractIdBibliotecaRoute: typeof AppContractsContractIdBibliotecaRoute
  AppContractsContractIdChatRoute: typeof AppContractsContractIdChatRoute
  AppContractsContractIdCondutasRoute: typeof AppContractsContractIdCondutasRoute
  AppContractsContractIdDashboardRoute: typeof AppContractsContractIdDashboardRoute
  AppContractsContractIdExtracaoRoute: typeof AppContractsContractIdExtracaoRoute
  AppContractsContractIdMapaRoute: typeof AppContractsContractIdMapaRoute
  AppContractsContractIdMapeamentoRoute: typeof AppContractsContractIdMapeamentoRoute
  AppContractsContractIdMelhoriasDocRoute: typeof AppContractsContractIdMelhoriasDocRoute
  AppContractsContractIdNormalizacaoRoute: typeof AppContractsContractIdNormalizacaoRoute
  AppContractsContractIdPlanoAcaoRoute: typeof AppContractsContractIdPlanoAcaoRoute
  AppContractsContractIdRmaRoute: typeof AppContractsContractIdRmaRouteWithChildren
  AppContractsContractIdSubcontratosRoute: typeof AppContractsContractIdSubcontratosRoute
  AppContractsContractIdTimelineRoute: typeof AppContractsContractIdTimelineRoute
  AppContractsContractIdVistoriaImagemRoute: typeof AppContractsContractIdVistoriaImagemRoute
  AppContractsContractIdIndexRoute: typeof AppContractsContractIdIndexRoute
  AppContractsContractIdChecklistSetorRoute: typeof AppContractsContractIdChecklistSetorRoute
  AppContractsContractIdContabilCapituloRoute: typeof AppContractsContractIdContabilCapituloRoute
  AppContractsContractIdContabilOperacaoRoute: typeof AppContractsContractIdContabilOperacaoRoute
  AppContractsContractIdContabilPericialRoute: typeof AppContractsContractIdContabilPericialRoute
  AppContractsContractIdControleDocumentalAreasRoute: typeof AppContractsContractIdControleDocumentalAreasRoute
  AppContractsContractIdControleDocumentalDocumentosRoute: typeof AppContractsContractIdControleDocumentalDocumentosRoute
  AppContractsContractIdControleDocumentalOperacaoRoute: typeof AppContractsContractIdControleDocumentalOperacaoRoute
  AppContractsContractIdDesequilibrioBdiRoute: typeof AppContractsContractIdDesequilibrioBdiRoute
  AppContractsContractIdDesequilibrioEncargosRoute: typeof AppContractsContractIdDesequilibrioEncargosRoute
  AppContractsContractIdDesequilibrioGeradorClaimRoute: typeof AppContractsContractIdDesequilibrioGeradorClaimRoute
  AppContractsContractIdDesequilibrioIndiretosRoute: typeof AppContractsContractIdDesequilibrioIndiretosRoute
  AppContractsContractIdDesequilibrioInsumosRoute: typeof AppContractsContractIdDesequilibrioInsumosRoute
  AppContractsContractIdDesequilibrioPontuaisRoute: typeof AppContractsContractIdDesequilibrioPontuaisRoute
  AppContractsContractIdDesequilibrioValorAgregadoRoute: typeof AppContractsContractIdDesequilibrioValorAgregadoRoute
  AppContractsContractIdFinalizacaoJudicialRoute: typeof AppContractsContractIdFinalizacaoJudicialRoute
  AppContractsContractIdFinalizacaoLicoesRoute: typeof AppContractsContractIdFinalizacaoLicoesRoute
  AppContractsContractIdFinalizacaoPleitosRoute: typeof AppContractsContractIdFinalizacaoPleitosRoute
  AppContractsContractIdPreBasesRoute: typeof AppContractsContractIdPreBasesRoute
  AppContractsContractIdPreDiagnosticoRoute: typeof AppContractsContractIdPreDiagnosticoRoute
  AppContractsContractIdPreRevisaoRoute: typeof AppContractsContractIdPreRevisaoRoute
  AppContractsContractIdPreTranspasseRoute: typeof AppContractsContractIdPreTranspasseRoute
  AppContractsContractIdChecklistIndexRoute: typeof AppContractsContractIdChecklistIndexRoute
  AppContractsContractIdContabilIndexRoute: typeof AppContractsContractIdContabilIndexRoute
  AppContractsContractIdControleDocumentalIndexRoute: typeof AppContractsContractIdControleDocumentalIndexRoute
  AppContractsContractIdDesequilibrioIndexRoute: typeof AppContractsContractIdDesequilibrioIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppContractsNewRoute: AppContractsNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppContractsContractIdBibliotecaRoute: AppContractsContractIdBibliotecaRoute,
  AppContractsContractIdChatRoute: AppContractsContractIdChatRoute,
  AppContractsContractIdCondutasRoute: AppContractsContractIdCondutasRoute,
  AppContractsContractIdDashboardRoute: AppContractsContractIdDashboardRoute,
  AppContractsContractIdExtracaoRoute: AppContractsContractIdExtracaoRoute,
  AppContractsContractIdMapaRoute: AppContractsContractIdMapaRoute,
  AppContractsContractIdMapeamentoRoute: AppContractsContractIdMapeamentoRoute,
  AppContractsContractIdMelhoriasDocRoute:
    AppContractsContractIdMelhoriasDocRoute,
  AppContractsContractIdNormalizacaoRoute:
    AppContractsContractIdNormalizacaoRoute,
  AppContractsContractIdPlanoAcaoRoute: AppContractsContractIdPlanoAcaoRoute,
  AppContractsContractIdRmaRoute: AppContractsContractIdRmaRouteWithChildren,
  AppContractsContractIdSubcontratosRoute:
    AppContractsContractIdSubcontratosRoute,
  AppContractsContractIdTimelineRoute: AppContractsContractIdTimelineRoute,
  AppContractsContractIdVistoriaImagemRoute:
    AppContractsContractIdVistoriaImagemRoute,
  AppContractsContractIdIndexRoute: AppContractsContractIdIndexRoute,
  AppContractsContractIdChecklistSetorRoute:
    AppContractsContractIdChecklistSetorRoute,
  AppContractsContractIdContabilCapituloRoute:
    AppContractsContractIdContabilCapituloRoute,
  AppContractsContractIdContabilOperacaoRoute:
    AppContractsContractIdContabilOperacaoRoute,
  AppContractsContractIdContabilPericialRoute:
    AppContractsContractIdContabilPericialRoute,
  AppContractsContractIdControleDocumentalAreasRoute:
    AppContractsContractIdControleDocumentalAreasRoute,
  AppContractsContractIdControleDocumentalDocumentosRoute:
    AppContractsContractIdControleDocumentalDocumentosRoute,
  AppContractsContractIdControleDocumentalOperacaoRoute:
    AppContractsContractIdControleDocumentalOperacaoRoute,
  AppContractsContractIdDesequilibrioBdiRoute:
    AppContractsContractIdDesequilibrioBdiRoute,
  AppContractsContractIdDesequilibrioEncargosRoute:
    AppContractsContractIdDesequilibrioEncargosRoute,
  AppContractsContractIdDesequilibrioGeradorClaimRoute:
    AppContractsContractIdDesequilibrioGeradorClaimRoute,
  AppContractsContractIdDesequilibrioIndiretosRoute:
    AppContractsContractIdDesequilibrioIndiretosRoute,
  AppContractsContractIdDesequilibrioInsumosRoute:
    AppContractsContractIdDesequilibrioInsumosRoute,
  AppContractsContractIdDesequilibrioPontuaisRoute:
    AppContractsContractIdDesequilibrioPontuaisRoute,
  AppContractsContractIdDesequilibrioValorAgregadoRoute:
    AppContractsContractIdDesequilibrioValorAgregadoRoute,
  AppContractsContractIdFinalizacaoJudicialRoute:
    AppContractsContractIdFinalizacaoJudicialRoute,
  AppContractsContractIdFinalizacaoLicoesRoute:
    AppContractsContractIdFinalizacaoLicoesRoute,
  AppContractsContractIdFinalizacaoPleitosRoute:
    AppContractsContractIdFinalizacaoPleitosRoute,
  AppContractsContractIdPreBasesRoute: AppContractsContractIdPreBasesRoute,
  AppContractsContractIdPreDiagnosticoRoute:
    AppContractsContractIdPreDiagnosticoRoute,
  AppContractsContractIdPreRevisaoRoute: AppContractsContractIdPreRevisaoRoute,
  AppContractsContractIdPreTranspasseRoute:
    AppContractsContractIdPreTranspasseRoute,
  AppContractsContractIdChecklistIndexRoute:
    AppContractsContractIdChecklistIndexRoute,
  AppContractsContractIdContabilIndexRoute:
    AppContractsContractIdContabilIndexRoute,
  AppContractsContractIdControleDocumentalIndexRoute:
    AppContractsContractIdControleDocumentalIndexRoute,
  AppContractsContractIdDesequilibrioIndexRoute:
    AppContractsContractIdDesequilibrioIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
